### ISSUE TITLE
String field type does not always format to a string

### ISSUE THREAD

**Issue by boydgreenfield** [biosustain/potion#100]
I ran into an odd bug today where (for legacy reasons) I have an integer field in a database that I'd like to serve as a string in my API (but am still using elsewhere as an int... :frown:).

I was surprised to find that setting the field `val = fields.String(attribute='my_db_int_field')` led to Potion serving an int in the final JSON. I fixed this with a simple `CoercedString` field that adds a `formatter` method coercing it to a string, but should this be the default behavior? 

Relevant `String` definition for reference: https://github.com/biosustain/potion/blob/master/flask_potion/fields.py#L411-L438

Unfortunately, I'm not what's the most Python2/3-compatible way to do this coercion universally while still avoiding surprise corner cases. Thoughts on this @lyschoening?

**Comment by lyschoening** [comment]
On the formatting side, Potion does not do any type checking or automatic coercion. There is a significant performance overhead to having type checks at runtime in Python, so it is left up to the API developer to provide valid data to Potion.

I would recommend one of two approaches here: 

- Make a `@hybrid_property` (SQLAlchemy) or `@property` on the model that converts from/to `str`
- Use a custom field: `Custom({"type": "string", "pattern": "^\d+$"}, formatter=str, converter=int)`

**Comment by boydgreenfield** [comment]
Got it – that's very helpful, thanks for the design POV and suggestions @lyschoening (we had done 2). Closing this now.
