### ISSUE TITLE
Support SQLite's JSON1 extension?

### ISSUE THREAD

**Issue by deeplook** [biosustain/potion#102]
If this isn't yet on anybody's radar... Does it make sense to support this in Potion, in some sense maybe like `sqlalchemy.dialects.postgresql.JSONB` or would this be rather a challenge for SQLAlchemy?

- http://charlesleifer.com/blog/using-the-sqlite-json1-and-fts5-extensions-with-python/
- https://www.sqlite.org/draft/json1.html

**Comment by lyschoening** [comment]
This doesn't appear to have any connection to Potion? From what I understand JSON1 is just a collection of functions for manipulating JSON in SQLite, which are still stored as regular strings.
