### ISSUE TITLE
Missing ModelManager?

### ISSUE THREAD

**Issue by deeplook** [biosustain/potion#105]
There is no `ModelManager` in the code base as referenced here: http://potion.readthedocs.io/en/latest/recipes.html?highlight=ModelManager#archivingresource Is this missing or is the documentation maybe wrong? Any hints appreciated. Or would it be any of the persistence managers like SQLAlchemyManager, etc.?

**Comment by deeplook** [comment]
Moving forward, SQLAlchemyManager seems to be ok in my case. But a tiny hint in the doc might be in order.

**Comment by lyschoening** [comment]
Agreed and fixed.
