### ISSUE TITLE
Exposed schema endpoints

### ISSUE THREAD

**Issue by Alain1405** [biosustain/potion#108]
Even though I protect the generated API with authentication, the schema endpoints remain open:

```
decorators = [jwt_authentication_dec]
api_blueprint = Blueprint('api', __name__)
api = Api(api_blueprint, decorators=decorators, default_manager=principals(SQLAlchemyManager))
```

Any GET to `http://example.com/api/schema` or `http://example.com/api/res/schema` return the schema.

**Comment by lyschoening** [comment]
That has been intentional, but it is something that could be changed.

**Comment by Alain1405** [comment]
I thought people wouldn't be so willing to share their data model and custom endpoints by default.
Do you meant that there is a configuration or it's something that could be changed in code?

**Comment by lyschoening** [comment]
It is quite common to make the API schema public and in the past I’ve considered it a bug that the resource schemas are sometimes not public. There is no way to configure this currently, so a code change is required.

**Comment by lyschoening** [comment]
It makes sense for the endpoints to behave consistently though, so I will change this tomorrow unless you would like to create a PR.

**Comment by Alain1405** [comment]
I've only seen this now. 
I will have a look at it and see what I can do for making all endpoints consistent and open maybe have configurable open schema enpoints.

**Comment by Alain1405** [comment]
@lyschoening I have created a pull https://github.com/biosustain/potion/pull/110

I added the possibility of making the schema endpoint non-decorated via environmental variable, even though I don't like it much. 

What do you think? 
Also I'm not sure where is the best place for documenting the configuration.

**Comment by lyschoening** [comment]
@Alain1405 This appears fixed now in `master`. Let me know if the solution works for you.

**Comment by Alain1405** [comment]
It seems to work!
