### ISSUE TITLE
Issue using db.LargeBinary columns

### ISSUE THREAD

**Issue by rmilne** [biosustain/potion#109]
There is a unicode conversion error with flask-potion 0.12.7

```
File "/opt/python/run/venv/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 469, in do_execute
cursor.execute(statement, parameters)
TypeError: can't escape unicode to binary
```

How would I properly work around this and add base64 encoding/decoding?

```python
class File(db.Model):                                                           
    id = db.Column(db.Integer, primary_key=True)                                
    datatype = db.Column(db.String, nullable=False)                             
    filename = db.Column(db.String, nullable=False)                             
    data = db.Column(db.LargeBinary)                                            
    timestamp = db.Column(db.DateTime, default=db.func.now())                   
                                                                                
class FileResource(ModelResource):                                              
    class Meta:                                                                 
        model = File     
```

Thanks for making this project, it's nice.

**Comment by lyschoening** [comment]
The most straightforward way would be to create a new field (inherit from `fields.String`). You would override `.formatter()` and `.converter()` with the conversion logic. 

Then you can choose to manually specify the field in the schema like so:

```
class FileResource(ModelResource):                                              
    class Meta:                                                                 
        model = File  
    class Schema:
        data = BinaryField()
```

Or alternatively update the auto-detection in the manager, here: https://github.com/biosustain/potion/blob/master/flask_potion/contrib/alchemy/manager.py#L88

JSON schema itself has no good provisions for handling a badly encoded base64 string. If you want error handling to use the built-in validators you could specify a "regex" in the field schema or look into http://python-jsonschema.readthedocs.io/en/latest/validate/#validating-formats

**Comment by matthewfeickert** [comment]
@rmilne Is this the solution that you went with? Or did you find another solution?

**Comment by rmilne** [comment]
> @rmilne Is this the solution that you went with? Or did you find another solution?

Wow, this was 2+ years ago, I'm 80% sure I went with the first suggestion and made my own field.  May have added zip compression to it as well.  It was a closed source project at a company I no longer work at unfortunately.

**Comment by matthewfeickert** [comment]
@rmilne Indeed it was a long time. Thanks for responding at all! :)

That information is still helpful, so thanks!
