### ISSUE TITLE
Lack of documentation for HybridRelationshipNeed and HybridItemNeed

### ISSUE THREAD

**Issue by galuszkak** [biosustain/potion#116]
Hi @lyschoening thanks for awesome tool and work on it!

I have a question, there is no documentation for HybridItemNeed and HybridRelationshipNeed. I may probably need those, but trying to tackle how they work isn't so clear for me. HybridNeed also mention `Hybrid needs can both be evaluated directly or produce an expression for use with SQLAlchemy.`, can be there included some example for that how use it to get some idea?

For example I want to restrict visibility of some resource based on user (As an example with issue tracker. User can see only issues to projects where he belongs to). I believe HybridNeed is something I need to use but I'm not entirely sure how and documentation didn't enlighten me yet ;).

Again thanks for awesome work on potion 👍

**Comment by lyschoening** [comment]
Hi @galuszkak,

Those classes are used internally by `PrincipalMixin`. They are not exposed by the API, that is why they are undocumented. 

The documentation for `PrincipalMixin` is over here: http://potion.readthedocs.io/en/latest/permissions.html

In your case, there are two approaches. If a user usually has access to a small number of projects, I recommend loading appropriate item needs when the user identity is created in Flask-Principals. You can find an example here: http://potion.readthedocs.io/en/latest/permissions.html#object-based-permissions

If a user has access to a large number of projects, you can use the `'user:{field}'` permission pattern, e.g. `{'read': 'user:project_owner'}`. This will grant read access to any identity that has a `UserNeed` with an id that matches the one of `Project.project_owner`.

**Comment by galuszkak** [comment]
Thanks @lyschoening it's quite helpful!

What if this is based on other entity than User? I knew about UserNeed but wanted to try thought about something different.

Example:
User is project administrator and he can only see other users who are only in projects where he is administrator? This goes through m2m table and it's more sophiscated than only issues tied to project. (Because users can be in many projects.) . How can I restrict that User resource? 

Apologise if I'm complicating it's just not so clear to me.

**Comment by lyschoening** [comment]
That currently isn't implemented, as discussed in the other issue. It's also not a very straightforward thing to add when you consider how those relationships would work. An easy workaround might be to create a ProjectMembership resource and embed all the relevant information there. Alternatively, you could make a custom manager with your own `_query()` implementation.

**Comment by galuszkak** [comment]
@lyschoening awesome! That was my initial thought but I was quite reluctant to that idea as I thought _query is private method and I shouldn't override it without really good reason use it.

Anyway thanks for explanation that make total sense :)
