### ISSUE TITLE
Does exist tools to generate doc with flask potion hyper schema ?

### ISSUE THREAD

**Issue by buxx** [biosustain/potion#118]
Hello,

I tried to generate final user documentation with tools like [doca](https://github.com/cloudflare/doca) without success. It seems hyper schema flask potion generated is not directly "ready" to be used with doc generators. 

Fail is from me or some things/actions are needed to use  hyper schema flask potion generation ?

Thank's,
Bux.

**Comment by lyschoening** [comment]
Hi, if you can point to specific issues that doca is having, maybe we can fix them. Flask-potion should certainly work with doc generators. There is not so much good tooling out there for JSON HyperSchema so we are planning to move to Swagger/OpenAPI in the medium term.

**Comment by buxx** [comment]
Happy to know you're planning to move to Swagger/OpenAPI. To reproduce my issue with doca:

With this Flask-Potion code and doca installed:

```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_potion import Api, ModelResource

app = Flask(__name__)
db = SQLAlchemy(app)

class Book(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(), nullable=False)
    year_published = db.Column(db.Integer)

db.create_all()

class BookResource(ModelResource):
    class Meta:
        model = Book

api = Api(app)
api.add_resource(BookResource)

if __name__ == '__main__':
    app.run()
```

Prepare doca exemple project:

1. `git clone git@github.com:cloudflare/doca.git`
2. `cd doca/example`
3. `doca init`
4. Add book.json `curl 127.0.0.1:5000/book/schema > book.json` (in `doca/example` folder)
5. `cd documentation`
5. Edit `schemas.js` file to add `book.json`like this:
```
import { fromJS } from 'immutable';

export default fromJS([
  require('../cart.json'),
  require('../product.json'),
  require('../book.json')
]);
```
6. `npm install`
7. `npm start`
8. Open URL `http://127.0.0.1:8000/`

doca display an error:

`ERROR in ../book.json
Module build failed: TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at Object.handleResolveSuccess (/home/bastien/Projects/potion_test_doc/doca/example/documentation/node_modules/json-schema-loader/lib/loader.js:18:21)
 @ ./schemas.js 9:95-118
 @ ./src/client/store.js
 @ ./src/client/index.js
 @ multi webpack-hot-middleware/client?path=http://192.168.1.91:8080/__webpack_hmr ./src/client/index.js`

**Comment by lyschoening** [comment]
@buxx looks like there is an open issue on doca for this: 

https://github.com/cloudflare/doca/issues/9
https://github.com/cloudflare/json-schema-loader/pull/3

The issue here is that the schema contains both the definition for the models and the for the links related to the model. There are references from the links to the model and that trips up doca.

**Comment by buxx** [comment]
Good to know ! Thank's. I subscribe to these issues.

**Comment by daminli** [comment]
Does potion support  Swagger/OpenAPI now?
