### ISSUE TITLE
Missing doc about validation process overloading ?

### ISSUE THREAD

**Issue by buxx** [biosustain/potion#122]
Hello,

I can't found in the documentation how overload validation process.My goal is to add validation who cannot be done with jsonschema. 

Example invented:  POST /users
Validation error: Maximum created user count  reached for the day

Where a dynamic callback/python code check somewere (database, etc) if maximum created user count  is reached.

Is it possible ? If yes can you say how, i can make a pull request to update doc.
bux.

**Comment by lyschoening** [comment]
You can raise exceptions from within flask routes that you define. You can also override any routes in ModelResource with your own implementation and you can implement your own Manager and raise exception from there. Your use case isn't a validation error and it's beyond the scope of the project.

**Comment by lyschoening** [comment]
Also, @buxx please consider using Gitter for questions.
