### ISSUE TITLE
More verbose error message (status 409)

### ISSUE THREAD

**Issue by blasrodri** [biosustain/potion#124]
Currently, when a constraint is not held, we get:

*** HTTPError: HTTPError({u'status': 409, u'message': u'Conflict'},)

It would be very helpful to know what column and constraint was violated. Hence, if the error message included that information, the solution to the problem can be made faster.

**Comment by lyschoening** [comment]
You will see that information if you have debug mode enabled. Unfortunately, the error messages from the database are not straightforward to parse so it is not easy to distil the information down to something that can be safely shown to public users.

**Comment by blasrodri** [comment]
Thanks @lyschoening
