### ISSUE TITLE
Make field filterable, but not readable

### ISSUE THREAD

**Issue by jas32096** [biosustain/potion#125]
I have a field on a ModelResource that I'd like to make filterable, but not readable or writable i.e. not in the request or response schema.

Is that supported? Where should I be looking if I'd like to implement that?
Here? https://github.com/biosustain/potion/blob/master/flask_potion/resource.py#L267

It's a column_property on my SQLAlchemy model that I'd like to avoid having to evaluate with every request, as it's only used for filtering.

**Comment by aethn** [comment]
You'd have to evaluate it on every request anyways...

**Comment by jas32096** [comment]
No. It's a deferred column_property. It's only evaluated when accessed. If it's not included in the response schema, it wouldn't accessed. It would only be evaluated when filtered upon

**Comment by lyschoening** [comment]
As things are now you would have to override Manager._init_filters(), which only creates filters for readable fields. The logic could be changed so that fields that are not readable are also included if they are explicitly listed in meta.filters.

**Comment by jas32096** [comment]
@lyschoening Thanks.

```python
def _init_filters(self, resource, meta):
    added = []
    if isinstance(meta.filters, dict):
        for filter in meta.filters.keys():
            if filter == '*': continue
            if filter not in resource.schema.readable_fields:
                added.append(filter)
                resource.schema.readable_fields[filter] = resource.schema.fields[filter]

    super()._init_filters(resource, meta)
    for filter in added: del resource.schema.readable_fields[filter]
```

and setting `io=''` on the field did the trick.
