### ISSUE TITLE
Allow POST to use id_attribute=null

### ISSUE THREAD

**Issue by averri** [biosustain/potion#128]
There is a very common idiom that uses the entity ID to verify if the entity is new or not. Getting the example from Potion documentation [here](http://potion.readthedocs.io/en/latest/quickstart.html#self-documenting-api) to illustrate, the following book has not been saved yet:

```json
{
    "$id": null,
    "title": "On the Origin of Species",
    "year_published": 1859
}
```

The use of `$id=null` signals that the book has not been saved, so the client side can manipulate it consistently. 

If the above data is sent to Potion an error is produced:

```bash
$ http -v :5000/book title="On the Origin of Species" year_published:=1859 $id=null
POST /book HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 73
Content-Type: application/json
Host: localhost:5000
User-Agent: HTTPie/0.9.9

{
    "": "null",
    "title": "On the Origin of Species",
    "year_published": 1859
}

HTTP/1.0 400 BAD REQUEST
Content-Length: 170
Content-Type: application/json
Date: Wed, 27 Dec 2017 13:04:25 GMT
Server: Werkzeug/0.12.2 Python/3.6.4

{
    "errors": [
        {
            "path": [],
            "validationOf": {
                "additionalProperties": false
            }
        }
    ],
    "message": "Bad Request",
    "status": 400
}
```

Potion should allow the `id_attribute` to be null.

**Comment by lyschoening** [comment]
You can achieve that effect by adding the following line after your resource class definition:

```
BookResource.schema.set('$id', fields.Integer(attribute='id', nullable=True))
```

To achieve that effect throughout your API you can create your own `CustomModelResource` and inherit from it.

Please note that this allows the user of the API to specify an $id and to change it. Not everybody wants to allow the user to set ids and therefore it is not enabled by default. You can control which operations allow changing the id with the `io` attribute. 

Please also note that in your example use of HTTPie you are not setting `"$id"` to `null`, but `""` to `"null"`.
