### ISSUE TITLE
Allow POST, PATCH and PUT to send body with id_attribute

### ISSUE THREAD

**Issue by averri** [biosustain/potion#129]
Considering the example from Potion [here](http://potion.readthedocs.io/en/latest/quickstart.html#self-documenting-api), it should be possible to send POST, PATCH and PUT using the `id_attribute`. Actually, it's not possible, Potion will return an error if sending the body with the `id_attribute`, like the example below.

```shell
http PATCH :5000/book/1  year_published:=1600 $id=1

HTTP/1.1 400 BAD REQUEST
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 170
Content-Type: application/json
Date: Wed, 27 Dec 2017 13:50:39 GMT

{
    "errors": [
        {
            "path": [],
            "validationOf": {
                "additionalProperties": false
            }
        }
    ],
    "message": "Bad Request",
    "status": 400
}
```

**Comment by mahomahomaho** [comment]
why it's duplicate, and is duplicate of which issue? I'm struggling with similar problem, and I don't know where is  solution discussed?

**Comment by lyschoening** [comment]
@mahomahomaho I left a comment in issue #128

**Comment by mahomahomaho** [comment]
Ok, so for me, it's not quite duplicate. If I get it right, @averri struggle with problem similar to mine. 

I mean, when I get something, with eg. axios, like
```axios.get("/api/event/123").then(response=>{this.abo = response.data})
```

and then, I change something and save it like that:
```axios.patch("/api/event/123", this.abo).then(.....)
```

Then I get error about additional property $id. To prevent it, I need to do the following:
```
delete this.abo.$id;
axios.patch("/api/event/123", this.abo)......
```

**Comment by lyschoening** [comment]
`{$id}` are generally not permitted in requests. The comment in the other issue describes how you can customize your API to override this. 

I also highly recommend using potion-node for any JavaScript application you are planning to write: https://github.com/biosustain/potion-node

**Comment by mahomahomaho** [comment]
I think that data which I got from API, should be ok to sent back to API. At least it works like that in other REST toolkits known by me. 

Trick with schema is not obviously visible here, so I will repost it from #128:
```
 BookResource.schema.set('$id', fields.Integer(attribute='id', nullable=True))
```
