### ISSUE TITLE
Move Model documents to different files (MongoEngine) Example

### ISSUE THREAD

**Issue by wbashir** [biosustain/potion#130]
I am trying to figure out how I can create the `MongoEngine.Document` classes in separate files and still use the instance variable here:

https://github.com/biosustain/potion/blob/dc71f4954422f6edfde5bfa86f65dd622a35fdea/examples/mongoengine_simple.py#L12

Is there a good way of doing this so I can create a connection to the database and pass that mongo engine object around when i define my class modules in separate files?

**Comment by lyschoening** [comment]
This is more of a question for the Flask-MongoEngine community. 

The short answer is probably that you don't need to initialize `MongoEngine` with `app`. You can initialize it without the app reference in a different file, import it, and call `me.init_app(app)`.
