### ISSUE TITLE
v0.15.0 tag does not match master branch v0.15.0

### ISSUE THREAD

**Issue by corburn** [biosustain/potion#135]
Hello, I encountered a build error while packaging potion for [conda-forge](https://conda-forge.org/). The v0.15.0 tag commit hash does not match the master branch commit hash for the v0.15.0 release.

The commit hash for the master branch v0.15.0 release is: 8a42ccb21422d405cdb9a62319754e43477d2bc1

The commit hash for the v0.15.0 tag is: 7be8120694af23e0ac064facd77ee610e1593f22

In particular, the tagged branch still contains the deprecated pip import resolved in
f21c13773d4e45a38f524ae59acb5b5c671c72bc.

The issue is resolved, I just wanted to let you know about about the mismatch so you could fix the tag.

**Comment by lyschoening** [comment]
Thank you for bringing it up. This is fixed now.
