### ISSUE TITLE
Adding RefKey to inline field

### ISSUE THREAD

**Issue by matdrapeau** [biosustain/potion#141]
How can I add the refkey (usually seen as "$ref") to an sqlalchemy InlineModel field? 
Or if I want to add extra attributes to a ToOne field?

**Comment by lyschoening** [comment]
`{$ref}` objects usually stand alone. I am not sure I understand your question. Perhaps you want to use an `Inline` instead of a `ToOne` field?

**Comment by matdrapeau** [comment]
Let say I have a resource with this schema:

```
class Schema:
    title = fields.String()
    description = fields.String()
    users = fields.List(alchemy.fields.InlineModel( {
                          'name': fields.String(),
                          'email': fields.String(),
                          '$ref': ???},
                          model=User))
```
How can I add the reference to the User resource (such as '/user/1' by example) in this current schema without using `fields.ToMany` since that users attribute should display more information than just a single '$ref'.

**Comment by matdrapeau** [comment]
Or possibly, I wouldn't mind describing my schema such as:
```
class Schema:
    title = fields.String()
    description = fields.String()
    users = fields.List(fields.ToMany('users'))
```
But how could I add 'name' and 'email' attributes to each users?

**Comment by lyschoening** [comment]
Have you tried `users = fields.List(fields.Inline('user'))`?

**Comment by matdrapeau** [comment]
That's working as expected with `fields.Inline` thanks!
