### ISSUE TITLE
Natural key in fields.ToOne

### ISSUE THREAD

**Issue by matdrapeau** [biosustain/potion#143]
How could it be possible to output the natural key when we reference it by a `fields.ToOne`.
Let say I have this:
```
class PersonResource(ModelResource):
    class Meta:
        model = Person
        natural_key = ('first_name', 'last_name')

class BookResource(ModelResource):
    class Meta:
        model = Book
    class Schema:
        author = fields.ToOne('persons')
```

When I issue ` GET /book/1` I am currently getting this output for the author  `{'$ref': '/persons/1'}`
How can I get the natural key being output as the author instead like: `['Stephen', 'King']`

**Comment by lyschoening** [comment]
The natural key is only for requests, not for responses. You can override this by changing the order of the `key_converters`.

https://github.com/biosustain/potion/blob/1bdc0ee75ab533230e26a0328ef1c2a8eb0dc3b6/flask_potion/resource.py#L321-L324
