### ISSUE TITLE
Accessing subset of data based on arbitrary identifiers

### ISSUE THREAD

**Issue by matdrapeau** [biosustain/potion#149]
I am not sure what would be the best way to handle restricting data based on session identifiers.
I don't really want use Flask-Principal which seems too complex and overkill.

So, I would like to find a way to adapt Resource actions based on a user session.

By example:
` /books`
would filter only the books with the author id is stored in the flask session `author_id`.
Edits and deletes should verify that you own them by looking at the session variable.

How would be a good approach to handle that?

**Comment by lyschoening** [comment]
You'll want to update the instances method of your resource's Manager: https://potion.readthedocs.io/en/latest/managers.html#flask_potion.manager.Manager.instances

One approach is to use the permission system based on Flask-Principal: https://potion.readthedocs.io/en/latest/permissions.html
