### ISSUE TITLE
Use of pattern_properties is not clear

### ISSUE THREAD

**Issue by albertodonato** [biosustain/potion#158]
I want to define an `Object` with `patternProperties`, basically to return a schema-free dict.

Looking at the doc it seems you'd do this with `fields.Object(pattern_properties={'.*': MyValueSchema})`, but this just returns a dict with `".*"` as key.

What's the correct way of defining an object with `patternProperties`?

**Comment by albertodonato** [comment]
So, I managed to get this working with `fields.Object(pattern='.*', properties=MyValueSchema)` but it seems it should be possible to use `pattern_properties` for that same purpose, which would be more straightforward.

**Comment by albertodonato** [comment]
@lyschoening could you please advise on the above?

**Comment by albertodonato** [comment]
@lyschoening I tired, that, but I get no patternProperties entries in my schema that way:

using `fields.Object(pattern='.*', properties=MyValueSchema)` I get

```
        {
            "href": "/my-resource",
            "method": "GET",
            "rel": "myResource",
            "targetSchema": {
                "additionalProperties": false,
                "patternProperties": {
                    ".*": {
                        "default": [],
                        "items": {
                            "type": "string"
                        },
                        "type": "array"
                    }
                },
                "type": "object"
            }
        },
```

wherease `fields.Object(pattern_properties={'.*': fields.Raw(MyValueSchema)})` gives:

```
        {
            "href": "/my-resource",
            "method": "GET",
            "rel": "myResource",
            "targetSchema": {
                "additionalProperties": false,
                "type": "object"
            }
        },
```

**Comment by albertodonato** [comment]
FTR, `MyValueSchema = fields.Array(fields.String())` in this example

**Comment by lyschoening** [comment]
What does `fields.Object(pattern_properties={'.*': MyValueSchema})` give you?

**Comment by albertodonato** [comment]
Same as with `fields.Raw(MyValueSchema)`, I get no `patternProperties.` FTR this is exactly what I initially tried.

**Comment by albertodonato** [comment]
@lyschoening I'm not entirely sure it's the right fix, but the following works for me:

```diff
diff --git a/flask_potion/fields.py b/flask_potion/fields.py
index 8a20a43..b7eed77 100644
--- a/flask_potion/fields.py
+++ b/flask_potion/fields.py
@@ -281,6 +281,8 @@ class Object(Raw, ResourceBound):
 
         if isinstance(pattern_properties, (type, Raw)):
             self.pattern_properties = _field_from_object(self, pattern_properties)
+        else:
+            self.pattern_properties = pattern_properties
 
         def schema():
             request = {"type": "object"}
```

With this I can use `fields.Object(pattern_properties={'.*': MyValueSchema})` and it will set `patternProperties` in the resulting schema
