### ISSUE TITLE
$istartswith, $iendswith case-insensitive string filters

### ISSUE THREAD

**Issue by lyschoening** [biosustain/potion#19]

**Comment by yurimalheiros** [comment]
Hi, I am trying to implement these filters. I had some progress creating the filters for the alchemy and peewee backends, but I can't discover what is the role of the Comparators definitions in instances.py (line 24, where the variable DEFAULT_COMPARATORS is created). I'll be very glad if you can elucidate
this, specially the expression part of the Comparator. For instance:

```python
Comparator('$endswith',  # TODO case insensitive
               lambda field: {
                   "type": "string",
                   "minLength": 1
               },
               lambda ew, value: value and value.endswith(ew),
               (fields.String,)),
```

Why the lambda expression does something similar to the filter in alchemy or peewee backends? This endswith() method is a method of the columns of alchemy or peewee, or is this a method of string?

Thank you in advance.

**Comment by lyschoening** [comment]
@yurimalheiros  `DEFAULT_COMPARATORS` is a list of all comparators. Not all backends will necessarily support all of them. I've called it "default" because I considered implementing additional comparators for specific backends. Each `Comparator()` specifies a function to generate its JSON schema, an in-memory comparison operator, and a tuple with the field types it supports.

In addition to adding a comparator to `DEFAULT_COMPARATORS`, each backend also needs a backend-specific implementation and have the name added to `Manager.supported_comparators`.

**Comment by yurimalheiros** [comment]
So, the expression in the comparators is used in MemoryManager, right? I think there is no test for this manager.

**Comment by lyschoening** [comment]
`MemoryManager` is used for testing, but it is not supposed to be used in production so there are no further tests for it alone.
