### ISSUE TITLE
Failure on the Relationships example straight from the documentation

### ISSUE THREAD

**Issue by jacquerie** [biosustain/potion#25]
Hi, I was evaluating your library and I didn't manage to get the Relationships example working. Here's what I see. In a first shell I run:
```text
$ python potion.py 
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [10/Apr/2015 10:03:36] "POST /author HTTP/1.1" 200 -
127.0.0.1 - - [10/Apr/2015 10:03:37] "POST /book HTTP/1.1" 200 -
127.0.0.1 - - [10/Apr/2015 10:03:37] "POST /author HTTP/1.1" 200 -
127.0.0.1 - - [10/Apr/2015 10:03:37] "POST /book HTTP/1.1" 200 -
127.0.0.1 - - [10/Apr/2015 10:03:37] "GET /author/1/books HTTP/1.1" 404 -
```
In another shell I run:
```text
$ ./potion.sh 
HTTP/1.0 404 NOT FOUND
Content-Length: 233
Content-Type: text/html
Date: Fri, 10 Apr 2015 08:03:37 GMT
Server: Werkzeug/0.10.4 Python/2.7.8
 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```
and you can check the contents of `potion.py` and `potion.sh` here: https://gist.github.com/jacquerie/ec0ad2ee35e8f361a835.

**Comment by lyschoening** [comment]
Ah yes, the documentation is missing the line `books = Relation(‘book’)`. I will fix that. In the mean time, you can find the working example code here:

https://github.com/biosustain/potion/blob/master/examples/quickstart_relation.py <https://github.com/biosustain/potion/blob/master/examples/quickstart_relation.py>

Another way to make the query (one that also works with your code) is:

	http GET :5000/book where=='{"author”: 1}’
