### ISSUE TITLE
Many to Many and routes

### ISSUE THREAD

**Issue by bolerodan** [biosustain/potion#26]
So I have 2 models. Users and roles. A Role can belong to many users and a user may belong to many roles.

Following some of the examples I'm just stumped on how I would represent this in the schema where I can post to a route to add a user to a role.

I have the following models
```
roles_users = db.Table('roles_users',
                       db.Column(
                           'user_id',
                           db.Integer(),
                           db.ForeignKey('user.id')),
                       db.Column('role_id',
                                 db.Integer(),
                                 db.ForeignKey('role.id')))
```

```
class Role(db.Model):

    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(255))
    users = db.relationship('User', secondary=roles_users,
                           backref=db.backref('roles', lazy='dynamic'))
```
```
class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    firstname = db.Column(db.String(), nullable=False)
    lastname = db.Column(db.String(), nullable=False)
```

Following routes
```
class RoleResource(ModelResource):
    users = Relation('user')
    class Meta:
        model = Role

class UserResource(ModelResource):

    class Meta:
        model = User
```

viewing the schema of route, I can see  /role/{id}/users however attempting to GET that route I receive a 400 Bad request.

I can POST to that resource, passing in a user ID returning the user ref as a response, however I do notice the roles_users table doesnt actually update. However, trying to delete via /role/{id}/user/{id} results in a  ValueError: list.remove(x): x not in list error. But funny enough, passing in an id for a user that does not exist, results in a correct "user not found" error message.

I'm clearly configuring this wrong or defining something wrong, so hopefully you can help me achieve what I'm attempting to do.

Thanks!

**Comment by lyschoening** [comment]
Ok, I've fixed the first part of this in 0.7.4. Leaving the issue open for the ValueError when attempting to delete something that is not in the collection.

As general advice, I would recommend not using Relation(). A more RESTful practice would be to make a RoleMembership model and resource.
