### ISSUE TITLE
Maximum recursion depth exceeded: Feature request too.

### ISSUE THREAD

**Issue by bolerodan** [biosustain/potion#27]
So I found a way to cause a recursion depth.

Following this example.

```
class UserResource(PrincipalResource):

    class Meta:
        model = User

    class Schema:
        roles = fields.List(fields.Inline('role'))
```
```
class RoleResource(PrincipalResource):
    class Meta:
        model = Role
    class Schema:
        users = fields.List(fields.Inline('user'))
```

Users will show a field of roles, but roles, also show a list of users, but this then will cause a recursion as it keeps going, resulting in the python error maximum recursion depth exceeded.

I found this out basically because there are times, where you just want to show fields in a resources object for handy sake but not necessarily act on that field specifically.

An example of maybe "expanding" nested resources or relationships is by using a URL query parameter "expand". By default the resource will not show roles in the users response schema, and vice versa, unless manually specified via /user/?expand="roles".  Now I'm pretty sure you can go further, you can specify nested expands such as ?expand="roles.subfield" would expand the roles object and then further, the roles subfield (example name) object. Expand can have multiple resources expanded separated via commas. ?expand="users,invoices,inventory" etc.

Example APIs that use expand are 
https://stripe.com/docs/api#expanding_objects
http://venkat.io/posts/expanding-your-rest-api/
https://jira.atlassian.com/rest/api/latest/issue/JRA-9?expand=names,renderedFields

Just something to ponder about.

Thanks for your work!

**Comment by lyschoening** [comment]
So I am completely aware of this example of recursion. This simply shouldn't be done. At least one of the models should have a `ToMany` field instead of `Inline` and ideally both. Potion is designed with HTTP/2 and client-side caching in mind, and inlining messes with that whole concept when used excessively.

**Comment by lyschoening** [comment]
Having said that though, it would not be particularly difficult to implement a new `Resource` class that supports an expand parameter like you describe.

**Comment by bolerodan** [comment]
Yeah the more and more I've been tinkering with flask-potion (love it, by the way) the more I am seeing edge cases for the use of Inline.

There are just times where a resource may just need to expand its nested relationships because maybe at a point in time of the application those resources may not actually be cached client side, and would cut back on calls to the server as well.

Thanks again.

**Comment by lyschoening** [comment]
At one point server-side push could be used to send related items. Even then it should not by default send related items more than one level deep.

**Comment by bolerodan** [comment]
I agree about the more than one level deep.
