### ISSUE TITLE
write_only_fields doesn't omit field from JSON object

### ISSUE THREAD

**Issue by kolanos** [biosustain/potion#30]
Before I submit a pull request for this, I want to make sure I am clear on the expected behavior. When I do something like:

    class UserResource(ModelResource):
        class Meta:
            write_only_fields = ['password']

The `password` field continues to appear in JSON responses. But if I add it to `exclude_fields` it complains that `password` is an unexpected field when I try to include it in a request.

How is it supposed to work? My initial understanding was that `write_only_fields` should keep the field in the schema definition but exclude it from being included in all read responses.

**Comment by lyschoening** [comment]
There was a bug in `FieldSet.format()`. It's supposed to work as you thought it would. `exclude_fields` is for when you want to completely exclude a field and `read_only_fields`/`write_only_fields` are for restricting read/write.
