### ISSUE TITLE
Allow disabling of base resource methods

### ISSUE THREAD

**Issue by kolanos** [biosustain/potion#41]
There may be a simple way to do this already, but I haven't come across it yet. But it would be useful to have a way to disable methods on a resource-by-resource basis. Specifically the ones that are provided by the ModelResource class.

For example...

    class ReadOnlyResource(ModelResource):
        class Meta:
            methods = {
                'create': False,
                'update': False,
                'destroy': False
            }

    class CreateOnlyResource(ModelResource):
        class Meta:
            methods = {
                'create': True,
                'read': False,
                'update': False,
                'destroy': False
            }

Then any method that is ``False`` returns a ``405``. Not sure if ``methods`` should default to ``True`` or ``False``, I would lean ``False`` but that would break from the current behavior of the base methods being accessible. Although defaulting to ``False`` would likely be a reduction in code for most situations, especially with inheritance. It would also be more Pythonic as making base methods available would be explicit instead of implicit.

**Comment by lyschoening** [comment]
With principals this would be:
```
    class Meta:
        permissions = {
                'read': 'no',
                'create': 'yes',
                'update': 'no'
        }
```

It would be straightforward to add either a resource type or a manager that supports this. When making a resource, the format could be:

```
class MyModelResource(ModelResource):
    class Meta:
        methods = {}
    # ...
    @Route.GET('', rel="instances")
    def instances(self, **kwargs):
        if not self.meta.methods.get('create', True):
             return None, 405
        return self.manager.paginated_instances(**kwargs)
    # ...
```

**Comment by kolanos** [comment]
I was thinking of this in addition to authentication/authorization. Basically you could disable a method on a resource entirely, regardless of auth, and return a ``405`` to let the client know that this method isn't supported. For example, many other REST frameworks default all write methods to ``405``. A ``401`` or ``403`` would imply that a method is accessible with the right auth.

**Comment by lyschoening** [comment]
It is now possible in `master` to disable individual routes by setting `Meta.disabled_routes` to the relation names of the routes. These are inherited, but can be reset in later routes. The routes simply are not registered with Flask for the given resource, so the response code will be 404 or 405 depending on whether or not there is still another method registered at the url rule of the disabled route.

I've also added the option to decorate individual routes via a `Meta.route_decorators` dictionary. This is more closely related to #36.

Finally, it is now possible to override individual Route methods at a time by simply redefining them. Before it was only possible to override a method for a url rule by completely rewriting the route.

What I still would like to do is reformat `principals` so it that it uses `Meta.disabled_routes` to disable any routes that are completely unavailable under a given permissions configuration. This will be part of the multi-backend refactor.

Leaving this issue open until it is documented.
