### ISSUE TITLE
Add basic filters for fields.Datetime()

### ISSUE THREAD

**Issue by brunsgaard** [biosustain/potion#47]
@lyschoening, it seems that filtering on datetime columns are not possible right now, is that correct? And do you agree that this is a project issue that should be fixed?

**Comment by lyschoening** [comment]
@brunsgaard Yes, there are currently no date filters, and I agree they should be added. I am in the progress of rewriting the filter system right now to make it easier to add new filters. This is something I expect to release some time this week.  What sort of filters were you thinking of and for what backend(s)? Equals, before, after, between ..?

**Comment by brunsgaard** [comment]
I am using the sqlalchemy backend and the filters you describe seems sufficient. By the way, is there an IRC or Slack channel, where the project is being discussed?

**Comment by lyschoening** [comment]
Not yet, but I have set up a Gitter now.

**Comment by brunsgaard** [comment]
Nice. I will join the room, when it is up. ;)

**Comment by lyschoening** [comment]
As mentioned before this is part of a larger refactoring process. I will publish a new release when all of this is fully documented, which might take me a few more days. You're welcome to try it out from `master` in the mean time.

**Comment by brunsgaard** [comment]
Will do! Thanks..
