### ISSUE TITLE
ContainsFilter generates bad filter schema w/ ToMany fields

### ISSUE THREAD

**Issue by boydgreenfield** [biosustain/potion#58]
Specifically, this causes [Potion-Client](https://github.com/biosustain/potion-client) to blow up:

```
"tags": {
        "additionalProperties": false,
        "properties": {
            "$contains": {
                "additionalProperties": false,
                "properties": {
                    "$ref": {
                        "format": "uri",
                        "pattern": "^\\/api\\/v1\\/tags\\/[^/]+$",
                        "type": "string"
                    }
                },
                "type": "object"
            }
        },
        "required": [
            "$contains"
        ],
        "type": "object"
    },
   ...
```

As it believes the filter is required (correctly from the schema I believe).

The schema should _probably_ look like this (which works for all of the ContainsFilters I've tested it on):

```
"tags": {
    "anyOf": [
        {
            "additionalProperties": false,
            "properties": {
                "$contains": {
                    "additionalProperties": false,
                    "properties": {
                        "$ref": {
                            "format": "uri",
                            "pattern": "^\\/api\\/v1\\/tags\\/[^/]+$",
                            "type": "string"
                        }
                    },
                    "type": "object"
                }
            },
            "required": [
                "$contains"
            ],
            "type": "object"
        }
    ]
},
```

**Comment by lyschoening** [comment]
This is a bug in potion-client then. Could you file an issue there? The schema is valid. The `"$contains"` attribute is required, but the `"tags"` property is still optional.

**Comment by boydgreenfield** [comment]
Filing a bug there, you're right – and using this `anyOf` fix locally in the meantime as that seems to resolve the issue while also being not _strictly_ incorrect (`anyOf` just needs to be an array of 1+ elements, it's not required to be 2+).

I've dug around a _bit_ but all the proxies in `Potion-Client` make it, well, not the easiest code base to dive right into.
