### ISSUE TITLE
ContainsFilter does not properly work with ToMany fields

### ISSUE THREAD

**Issue by boydgreenfield** [biosustain/potion#59]
As it tries to validate the `?where` query clause based on the `ToMany` schema (i.e., null or an array), instead of the contained `ToOne`.

**Comment by lyschoening** [comment]
Thanks for the PR. This is out now in 0.11.2. I've committed the fix on my end because I didn't want to take the other commit for now.

**Comment by boydgreenfield** [comment]
Perfect; and no problem.
