### ISSUE TITLE
Make ItemUri and Uri filterable?

### ISSUE THREAD

**Issue by boydgreenfield** [biosustain/potion#72]
Right now, `ItemUri` and `Uri` are not filterable. Is there a design rationale here, or would you take a PR for adding this in @lyschoening? 

Can quickly draft one up if wanted (have a tweaked version here).

**Comment by lyschoening** [comment]
The core issue with `Uri` (also with `DateString`/`DateTimeString`) is that the filter isn't correctly resolved for the `String` class when no filter is available that is more specific. There should be a search up the base classes to find the filter that works best.

`ItemUri` is a different case. It's strictly one-way and I don't feel that filtering by anything other than an exact match would be a very common scenario. It's already possible to set `Meta.include_id = True` and then filter on `$id`, which would be a better approach if the `$id` has enough meaning that one would want to filter by it. You can of course write a custom filter if you need that functionality for some reason.

**Comment by lyschoening** [comment]
Could you elaborate on why you want to filter by `$uri`? Would what I described above work for you?

**Comment by boydgreenfield** [comment]
@lyschoening the main use case for filtering by `$uri` is just having the ability to do a `$in` query on an array of items, recognizing of course that:
 
- (1) it's often better style to just request the individual objects directly (except when it's not); and 
- (2) while using `$id` supports this out of the box, you then lose the benefits of using `$uri`, and it seems appropriate that `Meta.include_id = False` vs. `True` not change the type of filtering possible via the API

**Comment by lyschoening** [comment]
I realize that HTTP/2, which would eliminate the roundtrip issue, isn't an option if the client is synchronous.

We could consider having a special `$id` filter available regardless of whether or not it is included with the items? It just seems a bit silly to filter items by URI, given that most of the information is redundant. We could implement a filter for `$uri`, which would require implementing `ItemUri. converter()`, but I wouldn't want that filter to be enabled by default.

**Comment by boydgreenfield** [comment]
@lyschoening – short term, just implementing the `converter()` method but not enabling by default seems like a good option. I'll put a PR together for that later today.

Longer term, maybe the `$id` filter isn't a bad idea... though using that does beg the question of if using `$uri` at all.
