### ISSUE TITLE
Exception when using response_schema=instances.Instances() on non-model Resource

### ISSUE THREAD

**Issue by mafrosis** [biosustain/potion#76]
I get an exception due to an undefined manager when using `response_schema=instances.Instances()` on a vanilla `Resource` type.

Some code - in this example `UserResource` proxies an upstream service which provides the actual data:

	class UserResource(Resource):
	    class Schema:
	        uuid = fields.UUID()
	        email = fields.String()

	    class Meta:
	        upstream = 'http://example.com:8886'

	    @routes.Route.GET('', rel='instances', response_schema=instances.Instances())
	    def instances(self, *args, **kwargs):
	        resp = requests.get(urljoin(self.meta.user_service, 'user')).json()
	        return resp

The stacktrace:

	  File "/usr/local/lib/python3.4/site-packages/flask_potion/__init__.py", line 146, in wrapper
	    resp = view(*args, **kwargs)
	  File "/usr/local/lib/python3.4/site-packages/flask_potion/routes.py", line 274, in view
	    return response_schema.format_response(response)
	  File "/usr/local/lib/python3.4/site-packages/flask_potion/instances.py", line 21, in format_response
	    if not isinstance(data, self._pagination_types):
	  File "/usr/local/lib/python3.4/site-packages/werkzeug/utils.py", line 73, in __get__
	    value = self.func(obj)
	  File "/usr/local/lib/python3.4/site-packages/flask_potion/instances.py", line 66, in _pagination_types
	    return self.resource.manager.PAGINATION_TYPES
	AttributeError: type object 'UserResource' has no attribute 'manager' 

I suspect we're just doing it wrong, but perhaps this should be handled or documented.

**Comment by lyschoening** [comment]
`Ìnstances()` and anything relating to models and items is only available through `ModelResource`. `Resource` is a basic Resource type you can extend and specify custom routes on.

In your situation you might want to use a `ModelResource` and write your own `Manager` implementation to forward the requests.

**Comment by mafrosis** [comment]
Thanks @lyschoening
