### ISSUE TITLE
Option to override default instance list

### ISSUE THREAD

**Issue by diegoponciano** [biosustain/potion#81]
I'm very used to overriding ```get_queryset``` in django-rest-framework, and I'd like to be able to do that using potion.   
It seems like potion gets the instance list in the method ```def _query(self):```, if using the SQLAlchemyManager.   
Should I just override this function? Or maybe I'm missing something.

**Comment by lyschoening** [comment]
Yes, that is the simplest approach.

**Comment by diegoponciano** [comment]
Ok, it just seemed wrong for being a private function. I'm closing it then!
