### ISSUE TITLE
Support `user:self` or `user:$id` or `user:$uri` in `PrincipalsMixin`

### ISSUE THREAD

**Issue by boydgreenfield** [biosustain/potion#82]
Currently, the `PrincipalsMixin` supports generating a `UserNeed` based on a `ToOne` reference field, e.g., `user:owner`.

It doesn't, however, seem to let you restrict access to generate a similar `UserNeed` for restricting access to a `User` resource directly.

Locally, I've hacked a solution that simply supports other field types [here](https://github.com/biosustain/potion/blob/master/flask_potion/contrib/principals/__init__.py#L74). Unfortunately, the downstream checks assume that the field has a `resource` attribute, which requires adding the `resource` onto the `ItemUri` field (whether at init or in the need method calls) or changing them.

Any thoughts on the most elegant solution @lyschoening? Happy to submit a PR if this is wanted/useful functionality.

**Comment by lyschoening** [comment]
This has been brought up before and should be included. `"user:$id"` or `"user:$uri"` would be a nice approach. They should be interchangeable even if only one or the other is used. 

> Unfortunately, the downstream checks assume that the field has a `resource` attribute, which requires adding the `resource` onto the `ItemUri` field (whether at init or in the need method calls) or changing them.

We could make `ItemUri` a `ResourceBound`, but maybe the issue can be avoided altogether if both `$uri` and `$id` resolve to `self.id_field`.

> Happy to submit a PR if this is wanted/useful functionality.

Yes, please! I would love to see what you have done so far.

**Comment by boydgreenfield** [comment]
@lyschoening OK I'll put something together. Bumped into an odd edge case while doing this, however, and would love your preferences.

The first change needed to support this is as simple adding a few lines to `contrib/principals/__init__.py` ([here](https://github.com/biosustain/potion/blob/master/flask_potion/contrib/principals/__init__.py#L66-L85)):

```python
elif ':' in need:
    role, value = need.split(':')
    field = self.resource.schema.fields[value]

    if field.attribute is None:
        field.attribute = value

    # TODO implement this for ToMany as well as ToOne
    if isinstance(field, ToOne):
        target = field.target

        if role == 'user':
            options.add(HybridUserNeed(field))
        elif role == 'role':
            options.add(RoleNeed(value))
        else:
            for imported_need in target.manager._needs[role]:
                if isinstance(imported_need, HybridItemNeed):
                    imported_need = imported_need.extend(field)
                options.add(imported_need)

    # Special case for user:$uri or user:$id allowing UserNeed on a UserResource directly
    elif role == 'user' and value in ["self", "$uri", "$id"]:
        need = HybridItemNeed('id', self.id_field, type_="users")  # type_ not actually used for 'id' field
        options.add(need)
```

*but*, this led to a big debugging saga here as I wanted to experiment around using a `username` as an exposed API `id_field`, but internally the primary key in the test database is still an integer `id`. It turns out that Flask-Security auto-generates a `Need('id', <USER_PRIMARY_ID>)` using `Flask-Principal` under the hood, which causes the following code in `HybridItemNeed` ([link](https://github.com/biosustain/potion/blob/master/flask_potion/contrib/principals/needs.py#L34-L37)):

```python
for need in g.identity.provides:
    if len(need) == len(prototype):
        if all(p is None or n == p for n, p in zip(need, prototype)):
            yield need[1]
```

to create bad joins downstream in the manager layer like `WHERE appuser.username IN (1L, "boydgreenfield")` as it yields the integer ID need generated in Flask-Security.

Preferences on:

* 1) Adding some type checking logic into the `HybridItemNeed` `identity_get_item_needs` call that would only return reasonable/correctly typed columns (gross, incomplete sketch below)

```
if all(p is None or n == p for n, p in zip(need, prototype)):
    if isinstance(need[1], six.integer_types) and "integer" in self.resource._schema["type"]:
        yield need[1]
    elif isinstance(need[1], six.string_types) and "string" in self.resource._schema["type"]:
        yield need[1]
    ...   # Maybe there's a library helper function to help with this check somewhere?
```

* 2) Checking the method against the fieldname (this would require not hard-coding `id` throughout)
* 3) Something else?

**Comment by lyschoening** [comment]
Do I understand your problem correctly here that you're using `User.username` as the id field with your `UserResource`, but your `UserNeed` contains `User.id`? This is of course problematic as the field you want to match against, `User.id`, is not available to the resource at all. 

In either case, I don't think this is a problem Potion needs to solve. Either change Flask-Security to specify the key you want to use with `UserNeed`, override the `current_user` Proxy used by Flask-Login so that `current_user.id` returns the username, or expose the `id` column as field to the Resource (doesn't even need to be readable).

`type_` should be `None` as it is not used with `UserNeed`.

**Comment by boydgreenfield** [comment]
@lyschoening – You're right that exposing the `User.id` (but making it unreadable) is probably the right solution here. I'll submit a PR with the basic outline above, plus a fix to `type_` (it has to be non-null right now because of the `__init__` method). 

Quick question: Is it possible to include `User.id` in the model, make it unreadable, _and_ have it not appear in the schema? The only reason I hadn't done that is that it feels a bit odd for it to, e.g., appear in the `where` and `sort` clause schemas. Thanks!

**Comment by lyschoening** [comment]
In which schemas does it appear? It should be hidden from all of them if it isn't readable or writable.

**Comment by boydgreenfield** [comment]
@lyschoening It appears in the `where` and `sort` clauses. Here's the snippet:

```
                    "sort": {
                        "additionalProperties": false,
                        "properties": {
                            "$uri": {
                                "description": "Sort by $uri in descending order if 'true', ascending order if 'false'.",
                                "type": "boolean"
                            },
                            "id": {
                                "description": "Sort by id in descending order if 'true', ascending order if 'false'.",
                                "type": "boolean"
                            },
...
```

but maybe I'm not setting it up properly. What `io` flag should I be using for non-readable/non-writable? 

Also – just opened a PR for you.
