### ISSUE TITLE
Filter for empty relation

### ISSUE THREAD

**Issue by diegoponciano** [biosustain/potion#86]
Is there a default filter I can use to exclude null foreign keys?  
I tried "$eq" with ```null```, ```None```, ```""``` and in all of them got either Http400 or  invalid schema.

**Comment by lyschoening** [comment]
`{"property": null}` should work provided the field is nullable.

**Comment by diegoponciano** [comment]
Tried with null, got a ```"None is not valid under any of the given schemas"``` error.  
It's a ```ToOne``` field, maybe I'm missing some config.

**Comment by diegoponciano** [comment]
I'm trying to filter the relationship field of the FK.  
My model looks like:

```
class Food(SurrogatePK, Model):
    long_desc = db.Column(db.String(250))
    common = relationship(
        "CommonFood", uselist=False, backref="food"
```
And the resources:

```
class CommonFoodResource(ModelResource):
    class Meta:
        model = CommonFood
        include_id = True


class FoodResource(ModelResource):
    class Meta:
        manager = FoodManager
        model = Food
        include_id = True

    class Schema:
        common = fields.ToOne('common_food')

```

**Comment by lyschoening** [comment]
Your `ToOne` field is not nullable. To allow it to be nullable, use `common = fields.ToOne(‘common_food’, nullable=True)`.

The default is different than for SQLAlchemy.

**Comment by diegoponciano** [comment]
I'm sorry, I thought the database field should be nullable.  Thanks, it's working now!
