### ISSUE TITLE
No way to manually serialize objects?

### ISSUE THREAD

**Issue by dabeeeenster** [biosustain/potion#89]
If I write my own route, that for example creates a new object, sometimes I would want to send that object back to the client as JSON. It's not possible to return a SQLAlchemy object - I get:
   
       raise TypeError(repr(o) + " is not JSON serializable")

Is there an easy way to pass Potion an obect and have it return the serialised form to the client?

**Comment by shipperizer** [comment]
pass the request or response schema to the route, that should make it work

**Comment by lyschoening** [comment]
As @shipperizer said: if you specify a response schema your object will be converted to JSON-serializable form.

e.g.
```
@Route.GET
def foo(self) -> fields.Object({ "name": fields.String() }):
   return Foo(name="foo")
```

**Comment by dabeeeenster** [comment]
Thanks. Is there any way to return an entire model/resource object?

**Comment by lyschoening** [comment]
Use `fields.Inline()`

**Comment by dabeeeenster** [comment]
Great thanks
