### ISSUE TITLE
/schema endpoints permissions?

### ISSUE THREAD

**Issue by jmagnusson** [biosustain/potion#96]
Wouldn't it make sense to disallow `/schema` endpoints from being accessed if the user doesn't have any of the access permissions listed? Or perhaps it's doable today? If so, how?

**Comment by lyschoening** [comment]
An unauthenticated user will not have any access to the /schema endpoints. If you want some custom permissions beyond that you only need to override the rel='described_by' route with your own implementation and add a permissions check of your choosing. 

I don't see granular permissions on /schema as something I would want to implement in the core library.
