### ISSUE TITLE
Add meta-info to schema

### ISSUE THREAD

**Issue by Alain1405** [biosustain/potion#97]
I would like to add to the schema fields that add some meta-information about the model.
An example could be to add a field "label"key" which says which of the keys in the model is to be used as label in form.
I wouldn't mind setting such meta information at sqlalchemy level but if I add it as a @property or as @hybrid_key I also have to register it in the schema section in potion

**Comment by lyschoening** [comment]
Hi Alain, you can use `class Meta` to add arbitrary meta information to a resource. JSON Schema only uses "title" and "description" properties, and you can include these with both `Meta` and fields (e.g. `field.String(description="The name of this item")`). If you have meta information beyond that, just include it as a new property in `Meta` and either edit the `described_by` route to include it in the schema, or add a new route that accesses that information:

```

class CustoModelResource(ModelResource):
    class Meta:
        custom = "foo"

    @Route.GET
    def custom_meta(self) -> fields.String(description="The custom meta information for this resource"):
        return self.meta.custom

```
